In [0]:
import numpy as np

Defining the sigmoid activation function and its derivative

In [0]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
  return x * (1 - x)

Entering input values for training

In [0]:
training_inputs = np.array([[0, 0, 1],
                           [1, 1, 1],
                           [1, 0, 1],
                           [0, 1, 1]])

Entering output values for the provided inputs

In [0]:
training_outputs = np.array([[0, 1, 1, 0]]).T

Generating random weights for each input

In [0]:
np.random.seed(1)

synaptic_weights = 2 * np.random.random((3, 1)) - 1
print('Random weights are')
print(synaptic_weights)

Random weights are
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


Training the network iteratively

In [0]:
for iteration in range(20000):
  input_layer = training_inputs
  
  outputs = sigmoid(np.dot(input_layer, synaptic_weights))

  error = training_outputs - outputs

  adjustments = error * sigmoid_derivative(outputs)

  synaptic_weights += np.dot(input_layer.T, adjustments)

print('Synaptic weights after training')
print(synaptic_weights)

print('Outputs after training')
print(outputs)

Synaptic weights after training
[[10.38040701]
 [-0.20641179]
 [-4.98452047]]
Outputs after training
[[0.00679672]
 [0.99445583]
 [0.99548516]
 [0.00553614]]
